export const routes = {
  home: "/",
  login: "/login",
  emailVerification: "/email-verify",
  users: "/users",
  createUser: "/users/create",
  overview: "/overview",
  websiteUrls: "/website-urls",
  createWebsiteUrl: "/website-urls/create",
  domains: "/domains",
  createDomain: "/domains/create",
  pendingUsers: "/pending-users",
  pendingDomains: "/pending-domains",
  accountInformation: "/account-information",
  notices: "/notices",
  supports: "/supports",
  createNotice: "/notices/create",
  createSupport: "/supports/create",
  profile: "/profiles",
  orders: "/orders",
  pendingOrders: "/pending-orders",
  packages: "/packages",
};
